# choose a docker image to use
image: node:14

pages:
  stage: deploy

  # cache node_modules
  cache:
    paths:
    - node_modules/

  # install dependencies and run build script
  script:
  - yarn
  - yarn build

  artifacts:
    paths:
    - public

  only:
    # Trigger a new build and deploy only when there is a push to the
    # branch(es) below
    - $CI_DEFAULT_BRANCH
