# choose a docker image to use
image: node:14

pages:
  stage: deploy

  # cache node_modules
  cache:
    paths:
    - node_modules/

  # install dependencies and run build script
  script:
  - yarn
  - yarn build

  artifacts:
    paths:
    - public

  only:
    variables:
    - $CI_PIPELINE_SOURCE == "web"               # allow manual jobs from web
    - $CI_COMMIT_REF_SLUG == $CI_DEFAULT_BRANCH  # autodeploy from master/main
