baseURL = "https://petterivaarala.gitlab.io/"
languageCode = "en-us"
title = "Notes"
theme = "hyde"

[Menus]
  main = [
      {Name = "Gitlab", URL = "https://gitlab.com/PetteriVaarala"},
      {Name = "Github", URL = "https://github.com/PetteriVaarala/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/petterivaarala/"}
  ]
[params]
  description = "from the sidelines"
  layoutReverse = true
