[tools]
node = "24.1.0"
pnpm = "10.11.0"

[tasks.init]
run = "pnpm install"
description = "Install dependencies"

[tasks.dev]
run = "pnpm dev"
description = "Start the development server with hot-reload"
depends = ["init"]

[tasks.build]
run = "pnpm build"
description = "Build the project for production"
depends = ["init"]

[tasks.start]
run = "pnpm start"
description = "Start the production server"
depends = ["init"]

[tasks.lint]
run = "pnpm astro check"
description = "Run the linter to check code quality"
depends = ["init"]

[tasks.test]
run = "pnpm test"
description = "Run the test suite"
depends = ["init"]

[tasks.preview]
run = "pnpm preview"
description = "Preview the production build locally"
depends = ["init"]

[tasks.format]
run = "pnpm exec prettier --write ."
description = "Format code according to style guidelines"
depends = ["init"]

[tasks.clean]
run = "pnpm clean"
description = "Clean build artifacts and cache"

[tasks.update-minor]
run = "pnpm update --interactive"
description = "Update dependencies to newest minor version"
depends = ["init"]

[tasks.update-latest]
run = "pnpm update --interactive --latest"
description = "Update dependencies to newest latest version"
depends = ["init"]
