name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "README.md"
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install
        shell: bash
        run: deno install

      - name: Build
        shell: bash
        run: deno run build

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
